### ISSUE TITLE
Add a restart button

### ISSUE THREAD

**Issue by Bhuvilol** [Bhuvilol/Naagin#1]
As the game ends, it shows the score of the player and terminates the program with no functional further buttons. I need a functional restart button just below the score at the termination of the game. I would like an exit button if user want to quit the window.

**Comment by Bhuvilol** [comment]
Align both buttons in horizontally or vertically.

**Comment by GeorgiosDrivas** [comment]
Hello @Bhuvilol ! I would like to work on this issue. Would you like to implement both restart and close game buttons, or just the restart one?

**Comment by Bhuvilol** [comment]
@GeorgiosDrivas Restart button is a need, close button can be a good add on to the interface. Have a shot on both buttons if time suits you.
